name: ci

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    needs: [discord-bot, game-coordinator]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
