name: game-coordinator

on:
  pull_request:
    branches:
      - master
    paths:
      - 'game-coordinator/**'
      - '.github/workflows/game-coordinator.yml'
  push:
    branches:
      - master
    paths:
      - 'game-coordinator/**'
      - '.github/workflows/game-coordinator.yml'
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./game-coordinator

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Copy build files
        run: cp -r ./build ../dist

  test:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Test
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push' && success()

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Deploy to Production
        run: echo "Unimplemented deployment step."

```
