name: game-coordinator

on:
  pull_request:
    branches:
      - master
    paths:
      - 'game-coordinator/**'
      - '.github/workflows/game-coordinator.yml'
  push:
    branches:
      - master
    paths:
      - 'game-coordinator/**'
      - '.github/workflows/game-coordinator.yml'


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./game-coordinator

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Copy build files
        run: cp -r . ../dist

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./game-coordinator
    needs: build
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Test
        run: npm run test

